// ─── Sustain-ED Level 1 — Complete Appliance Database ───
// Source: CEA India Ver 21.0, BEE India, IEA, U.S. DOE (LBNL), NSSO
// Emission Factor: 0.710 kg CO₂/kWh (CEA India FY 2024-25)

const CO2_FACTOR = 0.710; // kg CO₂ per kWh

// 15 primary interactable appliances for the checklist
export const INTERACTABLE_IDS = [
  'ceiling_fan', 'led_bulb', 'tv_smart', 'ac_1_5ton',
  'fridge', 'washing_machine', 'geyser', 'induction',
  'microwave', 'mixer_grinder', 'wifi_router', 'set_top_box',
  'led_tube', 'phone_charger', 'table_fan',
];

export const APPLIANCE_DATA = {
  ceiling_fan: {
    id: 'ceiling_fan',
    name: 'Ceiling Fan',
    icon: '\u{1F300}',
    room: 'Living Room',
    wattage: 70,
    usePerDay: '8 hr/day',
    daysPerYear: 300,
    monthlyKwh: 16.8,
    annualKwh: 202,
    co2PerYear: +(202 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: true,
    beeRated: 'Mandatory',
    standbyPower: 0,
    hiddenConsumer: false,
    personality: 'breezy',
    voiceRate: 0.95,
    voicePitch: 1.0,
    description: "I am the Ceiling Fan, the most-used appliance in Indian homes. I spin at 70 watts, keeping you cool for about 100 rupees per month. I use up to 20 percent of your household electricity. You can switch to a BLDC fan at 28 watts and save 60 percent energy.",
    researchNote: "Most-used appliance. Conventional induction motor. BEE rates on service value (air delivery/watt). Consumes up to 20% of Indian household electricity.",
    funFact: "A BLDC fan uses just 28W compared to 70W. That is like replacing a bike with a bicycle in energy terms.",
    source: 'BEE India S&L',
  },

  led_bulb: {
    id: 'led_bulb',
    name: 'Light Bulb (60W)',
    icon: '\u{1F4A1}',
    room: 'All Rooms',
    wattage: 60,
    usePerDay: '10 hr/day',
    daysPerYear: 365,
    monthlyKwh: 18,
    annualKwh: 219,
    co2PerYear: +(219 * CO2_FACTOR).toFixed(1),
    category: 'Lighting',
    essential: true,
    beeRated: 'No',
    standbyPower: 0,
    hiddenConsumer: false,
    personality: 'bright',
    voiceRate: 1.0,
    voicePitch: 1.2,
    description: "I am the Light Bulb, one of the most common appliances in every home. I use 60 watts of power and run for about 10 hours each day. Switching to an LED bulb that uses only 9 watts can save up to 80 percent energy.",
    researchNote: "A 60W incandescent bulb can be replaced by a 9W LED, saving 80% energy. India's UJALA scheme distributed 370M+ LED bulbs.",
    funFact: "Switching one 60W bulb to a 9W LED saves enough electricity in a year to charge your phone over 1,000 times.",
    source: 'BEE India S&L',
  },

  tv_smart: {
    id: 'tv_smart',
    name: 'Smart TV (43" LED)',
    icon: '\u{1F4FA}',
    room: 'Living Room',
    wattage: 75,
    usePerDay: '6 hr/day',
    daysPerYear: 365,
    monthlyKwh: 13.5,
    annualKwh: 164,
    co2PerYear: +(164 * CO2_FACTOR).toFixed(1),
    category: 'Electronics',
    essential: false,
    beeRated: 'Mandatory',
    standbyPower: '1–3W',
    standbyKwhYear: '9–26',
    hiddenConsumer: true,
    personality: 'funny',
    voiceRate: 1.05,
    voicePitch: 0.95,
    description: "I am your Smart TV. I use 75 watts when you are watching, but my Wi-Fi module stays active even in standby mode, drawing 1 to 3 watts for updates and voice assistants. Modern smart TVs use far less energy than old CRT TVs which used 80 to 150 watts.",
    researchNote: "Smart TVs have higher standby due to Wi-Fi module staying active for updates and voice assistants.",
    funFact: "Old CRT TVs used 80 to 150 watts. A modern Smart TV uses just 75 watts and is three times bigger.",
    source: 'BEE India S&L',
  },

  ac_1_5ton: {
    id: 'ac_1_5ton',
    name: 'AC (1.5 Ton Inverter)',
    icon: '❄️',
    room: 'Bedroom',
    wattage: 1300,
    usePerDay: '8 hr/day',
    daysPerYear: 150,
    monthlyKwh: 312,
    annualKwh: 1560,
    co2PerYear: +(1560 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: false,
    beeRated: 'Mandatory (ISEER)',
    standbyPower: '1–3W',
    standbyKwhYear: '9–26',
    hiddenConsumer: true,
    personality: 'cool',
    voiceRate: 0.85,
    voicePitch: 0.9,
    description: "I am the Air Conditioner, the biggest energy consumer in your home at 1,300 watts. A 5-star model uses about 800 to 1000 kilowatt hours per year, while a 3-star uses 1,100 to 1,300. Setting the temperature to 24 degrees instead of 18 degrees can save up to 25 percent energy.",
    researchNote: "Most popular AC size in India. 5-star: ~800–1000 kWh/yr vs 3-star: ~1100–1300 kWh/yr.",
    funFact: "Setting your AC to 24 degrees instead of 18 degrees saves 25 percent energy, and you will not even notice the difference.",
    source: 'BEE India S&L',
  },

  fridge: {
    id: 'fridge',
    name: 'Refrigerator (250L)',
    icon: '\u{1F9CA}',
    room: 'Kitchen',
    wattage: 150,
    usePerDay: '24 hr/day (cycles ~8 hr)',
    daysPerYear: 365,
    monthlyKwh: '36–65',
    annualKwh: '430–780',
    co2PerYear: '305–554',
    category: 'Cooling/Preservation',
    essential: true,
    beeRated: 'Yes (Star Rated)',
    standbyPower: '2–5W',
    standbyKwhYear: '18–44',
    hiddenConsumer: true,
    personality: 'calm',
    voiceRate: 0.9,
    voicePitch: 0.85,
    description: "I am the Refrigerator. I run 24 hours a day, but my compressor cycles on and off. A 5-star 250 litre model uses about 180 kilowatt hours per year, while a 1-star model uses over 400. The BEE label shows the exact annual energy use. Try not to open the door too often, because cold air escapes each time.",
    researchNote: "Runs 24/7 but compressor cycles. 5-star 250L: ~180 kWh/yr vs 1-star: ~400+ kWh/yr. BEE label shows exact annual kWh.",
    funFact: "Every time you open the fridge door for 30 seconds, the fridge uses extra energy to cool back down.",
    source: 'BEE India S&L',
  },

  washing_machine: {
    id: 'washing_machine',
    name: 'Washing Machine (7kg FL)',
    icon: '\u{1F455}',
    room: 'Bathroom',
    wattage: 420,
    usePerDay: '1 hr/day avg',
    daysPerYear: 200,
    monthlyKwh: 12.6,
    annualKwh: 84,
    co2PerYear: +(84 * CO2_FACTOR).toFixed(1),
    category: 'Motors/Laundry',
    essential: false,
    beeRated: 'Voluntary',
    standbyPower: '1–2W',
    standbyKwhYear: '9–18',
    hiddenConsumer: true,
    personality: 'dizzy',
    voiceRate: 1.1,
    voicePitch: 1.1,
    description: "I am the Washing Machine. I use 420 watts to clean your clothes. Front-loading machines use less water and energy than top-loading ones. Even when I appear to be off, I draw 1 to 2 watts in standby. Running full loads saves more energy than doing many small loads.",
    researchNote: "Front-loaders use less water & energy than top-loaders. BEE voluntary star rating.",
    funFact: "Washing with cold water can save up to 90 percent of the energy used for heating water.",
    source: 'BEE India S&L',
  },

  geyser: {
    id: 'geyser',
    name: 'Water Heater (Geyser)',
    icon: '\u{1F6BF}',
    room: 'Bathroom',
    wattage: 2000,
    usePerDay: '30 min/day',
    daysPerYear: 180,
    monthlyKwh: 30,
    annualKwh: 180,
    co2PerYear: +(180 * CO2_FACTOR).toFixed(1),
    category: 'Heating',
    essential: true,
    beeRated: 'Yes (Star Rated)',
    standbyPower: '0–5W',
    standbyKwhYear: '0–44',
    hiddenConsumer: false,
    personality: 'warm',
    voiceRate: 0.88,
    voicePitch: 0.8,
    description: "I am the Geyser, the highest wattage appliance in your home. At 2,000 watts, I am extremely powerful but used only for a short time. Heating water for just 10 minutes before your bath is enough. A solar water heater can replace me and save over 1,000 rupees per month.",
    researchNote: "Extremely high wattage, short use. Major saving if replaced with solar water heater. BEE star label mandatory.",
    funFact: "A solar water heater has zero running cost and can save over 12,000 rupees per year.",
    source: 'BEE India S&L',
  },

  induction: {
    id: 'induction',
    name: 'Induction Cooktop',
    icon: '\u{1F373}',
    room: 'Kitchen',
    wattage: 1500,
    usePerDay: '1.5 hr/day',
    daysPerYear: 365,
    monthlyKwh: 67.5,
    annualKwh: 810,
    co2PerYear: +(810 * CO2_FACTOR).toFixed(1),
    category: 'Heating/Cooking',
    essential: true,
    beeRated: 'Voluntary',
    standbyPower: '0–1W',
    hiddenConsumer: false,
    personality: 'sizzling',
    voiceRate: 1.0,
    voicePitch: 1.0,
    description: "I am the Induction Cooktop. At 1,500 watts I may seem energy-hungry, but I am 85 percent efficient compared to gas stoves at only 40 percent. I heat food faster, so the total energy used per meal is actually lower. Induction cooking is replacing LPG in modern Indian kitchens.",
    researchNote: "Replaces LPG. Very high wattage but 85% efficient vs 40% for gas. Essential if primary cooking method.",
    funFact: "Induction cooktops are over twice as efficient as gas stoves, 85 percent versus 40 percent.",
    source: 'BEE India',
  },

  microwave: {
    id: 'microwave',
    name: 'Microwave Oven',
    icon: '\u{1F4E1}',
    room: 'Kitchen',
    wattage: 1000,
    usePerDay: '30 min/day',
    daysPerYear: 300,
    monthlyKwh: 15,
    annualKwh: 150,
    co2PerYear: +(150 * CO2_FACTOR).toFixed(1),
    category: 'Heating/Cooking',
    essential: false,
    beeRated: 'Voluntary',
    standbyPower: '3–5W',
    standbyKwhYear: '26–44',
    hiddenConsumer: true,
    personality: 'buzzy',
    voiceRate: 1.05,
    voicePitch: 1.15,
    description: "I am the Microwave Oven. I use 1,000 watts when cooking, but my digital clock display runs 24 hours a day, drawing 3 to 5 watts continuously even when I am not cooking. That is 26 to 44 kilowatt hours per year just for showing the time. I am a hidden energy consumer.",
    researchNote: "HIDDEN CONSUMER: Digital clock display runs 24/7 even when not cooking, drawing 3–5W continuously.",
    funFact: "The microwave clock alone uses more electricity per year than charging your phone.",
    source: 'BEE India',
  },

  mixer_grinder: {
    id: 'mixer_grinder',
    name: 'Mixer Grinder',
    icon: '\u{26A1}',
    room: 'Kitchen',
    wattage: 600,
    usePerDay: '15 min/day',
    daysPerYear: 365,
    monthlyKwh: 4.5,
    annualKwh: 55,
    co2PerYear: +(55 * CO2_FACTOR).toFixed(1),
    category: 'Motors/Cooking',
    essential: true,
    beeRated: 'No',
    standbyPower: 0,
    hiddenConsumer: false,
    personality: 'energetic',
    voiceRate: 1.2,
    voicePitch: 1.3,
    description: "I am the Mixer Grinder. At 600 watts I am quite powerful, but I only run for about 15 minutes a day. My short burst usage keeps annual consumption very low at just 55 kilowatt hours per year. I am found in almost every Indian kitchen.",
    researchNote: "Universal Indian kitchen appliance. Short burst usage keeps annual consumption low.",
    funFact: "Despite being 600 watts, the mixer grinder uses less electricity per year than a single LED bulb left on all day.",
    source: 'Manufacturer specs',
  },

  wifi_router: {
    id: 'wifi_router',
    name: 'Wi-Fi Router',
    icon: '\u{1F4F6}',
    room: 'Living Room',
    wattage: '6–12',
    usePerDay: '24 hr/day',
    daysPerYear: 365,
    monthlyKwh: '4.3–8.6',
    annualKwh: '53–105',
    co2PerYear: '38–75',
    category: 'Electronics/Comms',
    essential: true,
    beeRated: 'No',
    standbyPower: 'Always On',
    standbyKwhYear: '53–105',
    hiddenConsumer: true,
    personality: 'nerdy',
    voiceRate: 1.0,
    voicePitch: 1.1,
    description: "I am the Wi-Fi Router. I am a hidden energy consumer, running 24 hours a day, 365 days a year, but most people forget about me because I only use 6 to 12 watts. A typical 6-watt router uses about 53 kilowatt hours per year. Nobody ever switches me off because everyone depends on internet.",
    researchNote: "HIDDEN CONSUMER: Runs 24/7/365 but overlooked due to low wattage. Typical 6W router = ~53 kWh/yr.",
    funFact: "The Wi-Fi router never sleeps. It runs 24 hours a day, 365 days a year.",
    source: 'Manufacturer; Airtel India; LBNL',
  },

  set_top_box: {
    id: 'set_top_box',
    name: 'Set-Top Box (DTH)',
    icon: '\u{1F4E6}',
    room: 'Living Room',
    wattage: '10–25',
    usePerDay: '6 hr active + 18 hr standby',
    daysPerYear: 365,
    monthlyKwh: '7–18',
    annualKwh: '88–219',
    co2PerYear: '62–155',
    category: 'Electronics/Entertainment',
    essential: false,
    beeRated: 'No',
    standbyPower: '8–15W',
    standbyKwhYear: '70–131',
    hiddenConsumer: true,
    personality: 'sneaky',
    voiceRate: 0.9,
    voicePitch: 0.85,
    description: "I am the Set-Top Box, one of the worst hidden energy consumers in your home. My standby power of 8 to 15 watts is nearly the same as when I am active. Most people never switch me off at the wall. The International Energy Agency has flagged me globally as a major energy waster. Simply turning me off at the plug can save a lot of energy.",
    researchNote: "WORST HIDDEN CONSUMER. Standby (8–15W) nearly equals active power. Most users never switch off at wall. IEA flagged globally.",
    funFact: "The set-top box wastes 70 to 131 kilowatt hours per year just in standby, which is more than a ceiling fan uses all year.",
    source: 'U.S. DOE; IEA; BEE India',
  },

  // ─── NON-INTERACTABLE (environmental) appliances ───
  bldc_fan: {
    id: 'bldc_fan',
    name: 'BLDC Ceiling Fan',
    icon: '\u{1F300}',
    room: 'Bedroom',
    wattage: 28,
    annualKwh: 81,
    co2PerYear: +(81 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: true,
    description: "I'm the BLDC Fan — 60% more efficient than regular fans!",
    source: 'BEE India S&L',
  },
  table_fan: {
    id: 'table_fan',
    name: 'Table/Pedestal Fan',
    icon: '\u{1F32C}\u{FE0F}',
    room: 'Any',
    wattage: 50,
    annualKwh: 72,
    co2PerYear: +(72 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: true,
    description: "I'm the portable fan — supplementary cooling for any room!",
    source: 'BEE / Manufacturer',
  },
  led_tube: {
    id: 'led_tube',
    name: 'Fluorescent Tube (40W)',
    icon: '💡',
    room: 'Kitchen/Living',
    wattage: 40,
    annualKwh: 116,
    co2PerYear: +(116 * CO2_FACTOR).toFixed(1),
    category: 'Lighting',
    essential: true,
    description: "I am the traditional Fluorescent Tube — I use 40W and can be replaced with an 18W LED tube to save 55 percent energy!",
    source: 'BEE India S&L',
  },
  ac_1ton: {
    id: 'ac_1ton',
    name: 'AC (1 Ton Inverter)',
    icon: '❄️',
    room: 'Bedroom/Living',
    wattage: 900,
    annualKwh: 1080,
    co2PerYear: +(1080 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: false,
    description: "I'm the 1 Ton AC — smaller but still a major energy user!",
    source: 'BEE India S&L',
  },
  tv_32: {
    id: 'tv_32',
    name: 'TV (32" LED)',
    icon: '📺',
    room: 'Living Room',
    wattage: 40,
    annualKwh: 88,
    co2PerYear: +(88 * CO2_FACTOR).toFixed(1),
    category: 'Electronics',
    essential: true,
    description: "I'm the basic LED TV — energy-efficient entertainment!",
    source: 'BEE India S&L',
  },
  phone_charger: {
    id: 'phone_charger',
    name: 'Phone Charger',
    icon: '\u{1F50C}',
    room: 'Bedroom',
    wattage: 15,
    usePerDay: '3 hr/day',
    daysPerYear: 365,
    monthlyKwh: 1.4,
    annualKwh: 16,
    co2PerYear: +(16 * CO2_FACTOR).toFixed(1),
    category: 'Electronics/Charging',
    essential: true,
    beeRated: 'No',
    standbyPower: '0.1–0.5W',
    standbyKwhYear: 4.4,
    hiddenConsumer: true,
    personality: 'sneaky',
    voiceRate: 1.0,
    voicePitch: 1.15,
    description: "I am the Phone Charger, a tiny hidden energy consumer. Even when your phone is fully charged, I draw 0.1 to 0.5 watts while sitting plugged in. That is called phantom power. Over a year, my standby alone wastes 4.4 kilowatt hours. Always unplug me when you are not charging.",
    researchNote: "U.S. DOE LBNL confirms idle chargers draw 0.1–0.5W. With 1.4 billion mobile users in India, phantom charger load is a significant national energy concern.",
    funFact: "If every Indian unplugged their charger when done, the country would save enough electricity to power a small city.",
    source: 'U.S. DOE LBNL; BEE India',
  },

  led_tube: {
    id: 'led_tube',
    name: 'Fluorescent Tube',
    icon: '\u{1F4A1}',
    room: 'Kitchen',
    wattage: 40,
    usePerDay: '8 hr/day',
    daysPerYear: 365,
    monthlyKwh: 9.6,
    annualKwh: 116,
    co2PerYear: +(116 * CO2_FACTOR).toFixed(1),
    category: 'Lighting',
    essential: true,
    beeRated: 'No',
    standbyPower: 0,
    hiddenConsumer: false,
    personality: 'bright',
    voiceRate: 0.95,
    voicePitch: 1.05,
    description: "I am the Fluorescent Tube, a traditional 40-watt light source found in kitchens across India. I contain a small amount of mercury and use a ballast to operate. While I provide good illumination, I consume twice the energy of modern LED tubes.",
    researchNote: "Fluorescent tubes use 40W compared to 18W for LED replacements. BEE recommends switching to LED tubes for 55% energy savings.",
    energySavingTip: "Replace me with an 18W LED tube to save over 55% energy and get 25,000+ hours of life instead of my 8,000 hours.",
    funFact: "A single fluorescent tube replaced with an LED tube saves about 64 kWh per year — enough to charge a smartphone for 3 years!",
    source: 'BEE India S&L',
  },

  table_fan: {
    id: 'table_fan',
    name: 'Table Fan',
    icon: '\u{1F32A}\u{FE0F}',
    room: 'Bedroom',
    wattage: 50,
    usePerDay: '6 hr/day',
    daysPerYear: 200,
    monthlyKwh: 9.0,
    annualKwh: 60,
    co2PerYear: +(60 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: true,
    beeRated: 'No',
    standbyPower: 0,
    hiddenConsumer: false,
    personality: 'breezy',
    voiceRate: 0.95,
    voicePitch: 0.95,
    description: "I am the Table Fan, a portable cooling companion at 50 watts. I run about 6 hours a day during summer. I am not BEE rated, but I use 30 percent less power than a ceiling fan.",
    researchNote: "Table fans typically use 40-60W. While not BEE rated in India, they offer localized cooling that can reduce AC dependency.",
    funFact: "A table fan can reduce the feels-like temperature by 3 to 4 degrees, which means you can set your AC 3 degrees higher.",
    source: 'BEE India; NSSO Survey',
  },
};

// ─── 3D Positions for all appliances ───
// All positions pulled inward from walls to prevent clipping when scaled
export const APPLIANCE_POSITIONS = {
  // Living Room
  ceiling_fan:    { pos: [-5, 2.85, -4],    rot: [0, 0, 0] },
  led_bulb:       { pos: [-3, 2.9, -6],     rot: [0, 0, 0] },
  tv_smart:       { pos: [-5, 1.0, -7.0],   rot: [0, 0, 0] },
  wifi_router:    { pos: [-8.5, 0.5, -2],   rot: [0, Math.PI / 2, 0] },
  set_top_box:    { pos: [-7, 0.35, -6.5],  rot: [0, 0, 0] },
  // Bedroom
  ac_1_5ton:      { pos: [9.0, 2.3, -4],    rot: [0, -Math.PI / 2, 0] },
  // Kitchen (moved z from 7.2-7.3 to 6.5 to stay inside back wall)
  fridge:         { pos: [-1.5, 0.9, 6.5],  rot: [0, Math.PI, 0] },
  induction:      { pos: [-7.5, 0.95, 6.5], rot: [0, Math.PI, 0] },
  microwave:      { pos: [-6.0, 1.15, 6.5], rot: [0, Math.PI, 0] },
  mixer_grinder:  { pos: [-4.0, 0.95, 6.5], rot: [0, Math.PI, 0] },
  // Bathroom (moved x from 9.7 to 9.0 to stay inside right wall)
  geyser:         { pos: [9.0, 2.0, 2],     rot: [0, -Math.PI / 2, 0] },
  washing_machine:{ pos: [5.5, 0.42, 6.5],  rot: [0, Math.PI, 0] },
  // Other appliances
  led_tube:       { pos: [-7, 2.85, 4],     rot: [0, 0, 0] },           // Kitchen ceiling
  phone_charger:  { pos: [5, 0.55, -7.0],   rot: [0, 0, 0] },           // Bedroom desk
  table_fan:      { pos: [3, 0.55, -5],     rot: [0, Math.PI / 4, 0] }, // Bedroom table
};

// ─── Quiz Questions — Phase 2 Appliance Discovery (with difficulty: 1=easy, 2=medium, 3=hard) ───
export const QUIZ_QUESTIONS = [
  {
    id: 'q1',
    difficulty: 1,
    question: 'Your family wants to reduce the electricity bill. Which of these should they consider replacing first?',
    options: ['Air Conditioner (1300W, used 8 hr)', 'Phone charger (15W)', 'Mixer grinder (600W, used 15 min)', 'Wi-Fi router (6W)'],
    correctIndex: 0,
    explanation: 'The AC uses the most energy overall (1300W × 8 hours = 10,400 Wh per day). Targeting the biggest consumer gives the biggest savings.',
    source: 'BEE India S&L',
  },
  {
    id: 'q2',
    difficulty: 1,
    question: 'You unplug your phone but leave the charger in the socket. Is it still using electricity?',
    options: ['No, chargers only work when a phone is connected', 'Only if the switch is broken', 'Only during daytime', 'Yes — idle chargers draw 0.1 to 0.5 watts continuously'],
    correctIndex: 3,
    explanation: 'Idle chargers draw phantom power (0.1–0.5W). Across 1.4 billion mobile users in India, this adds up to massive national energy waste.',
    source: 'U.S. DOE LBNL',
  },
  {
    id: 'q3',
    difficulty: 1,
    question: 'Meena walks into the kitchen and counts the appliances. Why does the kitchen typically have more appliances than other rooms?',
    options: ['Kitchens are closer to the main power line', 'Because appliances are cheaper for kitchens', 'Cooking, preservation, and food preparation need multiple specialized devices', 'Because kitchens are bigger'],
    correctIndex: 2,
    explanation: 'Kitchen has fridge, induction, microwave, mixer, LED tube — cooking and food storage require many specialized appliances.',
    source: 'D1 Dataset',
  },
  {
    id: 'q4',
    difficulty: 2,
    question: 'You turn off the TV using the remote. The set-top box light is still glowing. Is this a problem?',
    options: ['No, the light uses no electricity', 'Yes — the set-top box in standby wastes nearly as much power as when active (8-15W)', 'No, set-top boxes turn off automatically', 'Only if the light is red'],
    correctIndex: 1,
    explanation: 'Set-Top Box is the WORST hidden consumer. Its standby power (8–15W) nearly equals active power, wasting 70–131 kWh/year. IEA flagged it globally.',
    source: 'IEA; U.S. DOE',
  },
  {
    id: 'q5',
    difficulty: 2,
    question: 'Rohit says "My Wi-Fi router uses only 6W, so it wastes very little energy." Is he correct?',
    options: ['Yes, 6W is negligible', 'Only if he turns it off at night', 'No — it runs 24/7/365, so even 6W adds up to 53+ kWh per year', 'Wi-Fi routers use 0W when nobody is browsing'],
    correctIndex: 2,
    explanation: 'Wi-Fi routers run 24/7/365. A 6W router uses ~53 kWh/year — more than many realize. They are hidden energy consumers.',
    source: 'Airtel India; LBNL',
  },
  {
    id: 'q6',
    difficulty: 2,
    question: 'Your old ceiling fan runs at 70W. A shopkeeper offers a BLDC fan. By how much would your energy use drop?',
    options: ['Around 60% — BLDC fans use only 28W', 'Around 20%', 'Around 40%', 'Around 80%'],
    correctIndex: 0,
    explanation: 'A BLDC fan uses just 28W compared to 70W — that\'s a 60% energy saving, one of the easiest upgrades in any Indian home.',
    source: 'BEE India S&L',
  },
  {
    id: 'q7',
    difficulty: 2,
    question: 'Which appliance has the HIGHEST wattage rating in a typical Indian home?',
    options: ['Microwave at 1,000W', 'AC at 1,300W', 'Induction cooktop at 1,500W', 'Geyser (water heater) at 2,000W'],
    correctIndex: 3,
    explanation: 'The Geyser runs at 2,000 watts — the highest wattage appliance, though it is used briefly (30 min/day).',
    source: 'BEE India S&L',
  },
  {
    id: 'q8',
    difficulty: 3,
    question: 'Neha\'s mother says "Gas stove is better than induction because induction uses electricity." What would you tell her about efficiency?',
    options: ['She is right, gas is always better', 'Both are equally efficient', 'Induction is only 20% efficient', 'Gas stoves are 40% efficient while induction is 85% efficient — induction wastes less total energy'],
    correctIndex: 3,
    explanation: 'Induction cooktops are 85% efficient compared to gas stoves at just 40%. Despite using electricity, induction wastes less total energy per meal.',
    source: 'BEE India',
  },
  {
    id: 'q9',
    difficulty: 3,
    question: 'For every 1 kWh of electricity used in India, approximately how much CO₂ is released into the atmosphere?',
    options: ['0.710 kg', '0.500 kg', '0.900 kg', '1.200 kg'],
    correctIndex: 0,
    explanation: 'India\'s grid emission factor is 0.710 kg CO₂/kWh (CEA India Ver 21.0 FY 2024-25). Every unit of electricity saved reduces carbon emissions.',
    source: 'CEA India FY 2024-25',
  },
  {
    id: 'q10',
    difficulty: 3,
    question: 'Arjun sets the AC to 18°C and wraps himself in a blanket. His father says this wastes energy. How much energy could Arjun save by setting it to 24°C instead?',
    options: ['About 5%', 'About 25% — each degree saves ~6% energy', 'About 15%', 'About 50%'],
    correctIndex: 1,
    explanation: 'Each degree higher saves ~6% energy. Going from 18°C to 24°C (6 degrees) saves approximately 25% energy. Setting AC to 24°C is the BEE recommended temperature.',
    source: 'BEE India',
  },
];

// ─── Achievement Definitions ───
export const ACHIEVEMENTS = [
  { id: 'first_discovery', title: 'First Discovery', description: 'Interacted with your first appliance!', icon: '\u{1F50D}', trigger: 'interact_1' },
  { id: 'curious_mind', title: 'Curious Mind', description: 'Explored 3 different appliances', icon: '\u{1F9E0}', trigger: 'interact_3' },
  { id: 'halfway_there', title: 'Halfway There', description: 'Discovered 6 out of 12 appliances!', icon: '\u{1F3C3}', trigger: 'interact_6' },
  { id: 'almost_done', title: 'Almost Done!', description: 'Only 3 appliances left to find!', icon: '\u{1F525}', trigger: 'interact_12' },
  { id: 'appliance_master', title: 'Appliance Master', description: 'Explored all 15 appliances!', icon: '\u{1F3C6}', trigger: 'interact_15' },
  { id: 'quiz_whiz', title: 'Quiz Whiz', description: 'Scored 100% on the final quiz!', icon: '\u{1F393}', trigger: 'quiz_perfect' },
  { id: 'energy_expert', title: 'Energy Expert', description: 'Earned 3 stars on the quiz!', icon: '\u{2B50}', trigger: 'quiz_3stars' },
];

// ─── Level 1 Building Design — Task Interaction Positions ───
export const LEVEL1_TASK_POSITIONS = {
  // Task 1 — Install windows (Living Room wall, currently dark)
  task_window_living: { pos: [-5, 1.8, -7.9], label: 'Install Window Here', room: 'Living Room', task: 1 },
  // Task 2 — Cross ventilation (opposite wall from existing window)
  task_ventilation: { pos: [-9.9, 1.8, -4], label: 'Place Window for Cross Ventilation', room: 'Living Room', task: 2 },
  // Task 3 — Open curtains (bedroom window already has curtains)
  task_curtains: { pos: [5, 1.8, -7.9], label: 'Open Curtains', room: 'Bedroom', task: 3 },
  // Task 4 — Day/Night behavior (living room center)
  task_daynight: { pos: [-5, 1.5, -4], label: 'Day/Night Controls', room: 'Living Room', task: 4 },
  // Task 5 — Temperature action (bedroom, near AC)
  task_temperature: { pos: [7, 1.5, -4], label: 'Temperature Check', room: 'Bedroom', task: 5 },
};

// ─── Level 1 Building Design Quiz — Phase 1 ───
export const LEVEL1_QUIZ_QUESTIONS = [
  {
    id: 'l1q1',
    difficulty: 1,
    question: 'Rahul lives in a house with no windows. During the day, he always has to keep lights ON. What single change would fix this?',
    options: ['Add windows to let in natural sunlight', 'Buy brighter bulbs', 'Install solar panels on the roof', 'Use more candles'],
    correctIndex: 0,
    explanation: 'Windows bring in natural daylight, eliminating the need for artificial lights during the daytime — saving electricity every single day.',
  },
  {
    id: 'l1q2',
    difficulty: 1,
    question: 'A single window is open but the room still feels stuffy. What design principle is missing?',
    options: ['The window is too small', 'The ceiling fan is off', 'The door should be locked', 'Air needs an entry AND exit — openings on opposite walls'],
    correctIndex: 3,
    explanation: 'Cross ventilation requires openings on opposite sides so air enters from one side and exits the other, creating a natural breeze.',
  },
  {
    id: 'l1q3',
    difficulty: 1,
    question: 'It is 2 PM on a sunny day. Priya notices her electricity bill is high. She looks around and sees all curtains are closed and all lights are ON. What should she do first?',
    options: ['Turn on the AC to feel better', 'Open the curtains to use sunlight and switch off the lights', 'Close more windows to trap cool air', 'Complain to the electricity company'],
    correctIndex: 1,
    explanation: 'Open curtains during daytime let sunlight in, replacing the need for artificial lighting and reducing electricity bills.',
  },
  {
    id: 'l1q4',
    difficulty: 2,
    question: 'At 9 PM, Arjun wants to save energy. Which combination of actions makes the most sense?',
    options: ['Open all windows and turn off all lights', 'Keep everything ON — it is nighttime', 'Close curtains for insulation, use only the lights needed, and fan if warm', 'Open curtains wide for moonlight'],
    correctIndex: 2,
    explanation: 'At night: close curtains for privacy and insulation, use only required lights, and fan only when needed. No natural light is available at night.',
  },
  {
    id: 'l1q5',
    difficulty: 2,
    question: 'The thermometer shows 30°C outside and 28°C inside. You feel slightly warm. What is the SMARTEST first step?',
    options: ['Open windows on opposite walls for natural airflow', 'Set AC to 18°C maximum cooling', 'Call an electrician to check the wiring', 'Buy a new portable cooler'],
    correctIndex: 0,
    explanation: 'When the temperature difference is small, natural ventilation works well. Open windows on opposite sides for cross ventilation before reaching for the AC.',
  },
  {
    id: 'l1q6',
    difficulty: 2,
    question: 'A school wants to build a new classroom that uses minimum electricity. According to ECBC principles, what should they prioritize?',
    options: ['Air conditioning in every room', 'The most expensive building materials', 'Underground construction for cool temperatures', 'Large windows for natural light and cross ventilation'],
    correctIndex: 3,
    explanation: 'ECBC (Energy Conservation Building Code) emphasizes using natural light, ventilation, and smart design to reduce energy consumption without extra cost.',
  },
  {
    id: 'l1q7',
    difficulty: 2,
    question: 'Two identical rooms: Room A has windows on ONE wall only. Room B has windows on OPPOSITE walls. Which room needs LESS fan usage and why?',
    options: ['Room A — fewer windows means less dust', 'Room B — opposite windows create natural airflow, reducing fan dependency', 'Both rooms are the same', 'Room A — one wall means stronger wind'],
    correctIndex: 1,
    explanation: 'Room B benefits from cross ventilation — air flows naturally through opposite openings, keeping the room cool without electric fans.',
  },
  {
    id: 'l1q8',
    difficulty: 3,
    question: 'A family reduced their electricity bill by 35% without buying any new appliances. Which combination of actions most likely achieved this?',
    options: ['They added windows, opened curtains during day, and used natural ventilation before AC', 'They stopped using the kitchen entirely', 'They only used electricity between 6 PM and 6 AM', 'They switched to a different electricity provider'],
    correctIndex: 0,
    explanation: 'Good building design — natural light, open curtains, and cross ventilation — can significantly reduce electricity bills without any new purchases.',
  },
  {
    id: 'l1q9',
    difficulty: 1,
    question: 'Which of these is a FREE source of indoor lighting?',
    options: ['LED tube light', 'Battery-powered lamp', 'Sunlight through windows', 'Solar panel'],
    correctIndex: 2,
    explanation: 'Sunlight entering through windows is completely free and provides excellent illumination during daytime, replacing electric lights entirely.',
  },
  {
    id: 'l1q10',
    difficulty: 3,
    question: 'An architect says "The best energy-saving device is good building design." What does this mean?',
    options: ['Buildings should have no electricity at all', 'Only old buildings are energy efficient', 'Modern buildings always waste energy', 'Buildings with proper windows, ventilation, and orientation need fewer appliances to maintain comfort'],
    correctIndex: 3,
    explanation: 'Smart building design with proper window placement, cross ventilation, and orientation reduces the need for artificial lighting, fans, and AC — saving energy from day one.',
  },
];

// ─── Idle Chatter Lines ───
export const IDLE_CHATTER = [
  "Hey! I'm over here, come talk to me!",
  "Psst... want to know a secret about energy?",
  "Don't ignore me! I have important facts!",
  "Come closer, I won't bite... I'll just enlighten you! \u{1F4A1}",
  "Did you know I'm wasting energy right now? Come find out how!",
  "Hey Arjun! Over here! \u{1F44B}",
];
