// ─── Sustain-ED Level 1 — Complete Appliance Database ───
// Source: CEA India Ver 21.0, BEE India, IEA, U.S. DOE (LBNL), NSSO
// Emission Factor: 0.710 kg CO₂/kWh (CEA India FY 2024-25)

const CO2_FACTOR = 0.710; // kg CO₂ per kWh

// 12 primary interactable appliances for the checklist
export const INTERACTABLE_IDS = [
  'ceiling_fan', 'led_bulb', 'tv_smart', 'ac_1_5ton',
  'fridge', 'washing_machine', 'geyser', 'induction',
  'microwave', 'mixer_grinder', 'wifi_router', 'set_top_box',
];

export const APPLIANCE_DATA = {
  ceiling_fan: {
    id: 'ceiling_fan',
    name: 'Ceiling Fan',
    icon: '🌀',
    room: 'Living Room',
    wattage: 70,
    usePerDay: '8 hr/day',
    daysPerYear: 300,
    monthlyKwh: 16.8,
    annualKwh: 202,
    co2PerYear: +(202 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: true,
    beeRated: 'Mandatory',
    standbyPower: 0,
    hiddenConsumer: false,
    personality: 'breezy',
    voiceRate: 0.95,
    voicePitch: 1.0,
    description: "Hey there! I'm the Ceiling Fan — the most-used appliance in Indian homes! I spin at 70 watts, keeping you cool for about ₹100/month. I use up to 20% of your household electricity. Tip: switch to a BLDC fan (28W) and save 60% energy!",
    researchNote: "Most-used appliance. Conventional induction motor. BEE rates on service value (air delivery/watt). Consumes up to 20% of Indian household electricity.",
    funFact: "A BLDC fan uses just 28W vs my 70W — that's like replacing a bike with a bicycle in energy terms!",
    source: 'BEE India S&L',
  },

  led_bulb: {
    id: 'led_bulb',
    name: 'LED Bulb (9W)',
    icon: '💡',
    room: 'All Rooms',
    wattage: 9,
    usePerDay: '10 hr/day',
    daysPerYear: 365,
    monthlyKwh: 2.7,
    annualKwh: 33,
    co2PerYear: +(33 * CO2_FACTOR).toFixed(1),
    category: 'Lighting',
    essential: true,
    beeRated: 'Mandatory',
    standbyPower: 0,
    hiddenConsumer: false,
    personality: 'bright',
    voiceRate: 1.0,
    voicePitch: 1.2,
    description: "Hello! I'm the LED Bulb! I replaced the old 60W incandescent bulb and use just 9 watts — saving 80% energy! India's UJALA scheme distributed over 370 million LED bulbs. I cost only ₹16/month to run!",
    researchNote: "Replaces 60W incandescent. India UJALA scheme distributed 370M+ LED bulbs. 80% energy saving.",
    funFact: "370 million LED bulbs have been distributed under India's UJALA scheme — that's enough to light a small galaxy!",
    source: 'BEE India S&L',
  },

  tv_smart: {
    id: 'tv_smart',
    name: 'Smart TV (43" LED)',
    icon: '📺',
    room: 'Living Room',
    wattage: 75,
    usePerDay: '6 hr/day',
    daysPerYear: 365,
    monthlyKwh: 13.5,
    annualKwh: 164,
    co2PerYear: +(164 * CO2_FACTOR).toFixed(1),
    category: 'Electronics',
    essential: false,
    beeRated: 'Mandatory',
    standbyPower: '1–3W',
    standbyKwhYear: '9–26',
    hiddenConsumer: true,
    personality: 'funny',
    voiceRate: 1.05,
    voicePitch: 0.95,
    description: "Hey, eyes over here! 📺 I'm your Smart TV! I use 75 watts when you're binge-watching, but here's the plot twist — my Wi-Fi module stays active even in standby, drawing 1–3W for updates and voice assistants. Modern me uses far less than old CRT TVs (80–150W)!",
    researchNote: "Smart TVs have higher standby due to Wi-Fi module staying active for updates and voice assistants.",
    funFact: "Old CRT TVs used 80-150W. I use just 75W — and I'm three times bigger!",
    source: 'BEE India S&L',
  },

  ac_1_5ton: {
    id: 'ac_1_5ton',
    name: 'AC (1.5 Ton Inverter)',
    icon: '❄️',
    room: 'Bedroom',
    wattage: 1300,
    usePerDay: '8 hr/day',
    daysPerYear: 150,
    monthlyKwh: 312,
    annualKwh: 1560,
    co2PerYear: +(1560 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: false,
    beeRated: 'Mandatory (ISEER)',
    standbyPower: '1–3W',
    standbyKwhYear: '9–26',
    hiddenConsumer: true,
    personality: 'cool',
    voiceRate: 0.85,
    voicePitch: 0.9,
    description: "Chill... I'm the Air Conditioner. ❄️ I'm the biggest energy consumer in your home at 1,300 watts. A 5-star model uses ~800-1000 kWh/year vs a 3-star at ~1,100-1,300 kWh/year. Set me to 24°C instead of 18°C to save up to 25% energy!",
    researchNote: "Most popular AC size in India. 5-star: ~800–1000 kWh/yr vs 3-star: ~1100–1300 kWh/yr.",
    funFact: "Setting your AC to 24°C instead of 18°C saves 25% energy — and you won't even notice the difference!",
    source: 'BEE India S&L',
  },

  fridge: {
    id: 'fridge',
    name: 'Refrigerator (250L)',
    icon: '🧊',
    room: 'Kitchen',
    wattage: 150,
    usePerDay: '24 hr/day (cycles ~8 hr)',
    daysPerYear: 365,
    monthlyKwh: '36–65',
    annualKwh: '430–780',
    co2PerYear: '305–554',
    category: 'Cooling/Preservation',
    essential: true,
    beeRated: 'Mandatory',
    standbyPower: '2–5W',
    standbyKwhYear: '18–44',
    hiddenConsumer: true,
    personality: 'calm',
    voiceRate: 0.9,
    voicePitch: 0.85,
    description: "I'm the Refrigerator. 🧊 I run 24/7, but my compressor cycles on and off. A 5-star 250L model uses ~180 kWh/year vs a 1-star at 400+ kWh/year. My BEE label shows exact annual kWh. Don't open my door too often — cold air escapes!",
    researchNote: "Runs 24/7 but compressor cycles. 5-star 250L: ~180 kWh/yr vs 1-star: ~400+ kWh/yr. BEE label shows exact annual kWh.",
    funFact: "Every time you open my door for 30 seconds, I use extra energy to cool back down. Think before you browse!",
    source: 'BEE India S&L',
  },

  washing_machine: {
    id: 'washing_machine',
    name: 'Washing Machine (7kg FL)',
    icon: '👕',
    room: 'Bathroom',
    wattage: 420,
    usePerDay: '1 hr/day avg',
    daysPerYear: 200,
    monthlyKwh: 12.6,
    annualKwh: 84,
    co2PerYear: +(84 * CO2_FACTOR).toFixed(1),
    category: 'Motors/Laundry',
    essential: false,
    beeRated: 'Voluntary',
    standbyPower: '1–2W',
    standbyKwhYear: '9–18',
    hiddenConsumer: true,
    personality: 'dizzy',
    voiceRate: 1.1,
    voicePitch: 1.1,
    description: "Whoooosh! 🌀 I'm the Washing Machine! I spin at 420 watts, cleaning your clothes. Front-loaders like me use less water AND energy than top-loaders. Even when I look 'off', I draw 1-2W in standby. Full loads save more energy than multiple small loads!",
    researchNote: "Front-loaders use less water & energy than top-loaders. BEE voluntary star rating.",
    funFact: "Washing with cold water can save up to 90% of the energy used for heating water!",
    source: 'BEE India S&L',
  },

  geyser: {
    id: 'geyser',
    name: 'Water Heater (Geyser)',
    icon: '🚿',
    room: 'Bathroom',
    wattage: 2000,
    usePerDay: '30 min/day',
    daysPerYear: 180,
    monthlyKwh: 30,
    annualKwh: 180,
    co2PerYear: +(180 * CO2_FACTOR).toFixed(1),
    category: 'Heating',
    essential: true,
    beeRated: 'Mandatory',
    standbyPower: '0–5W',
    standbyKwhYear: '0–44',
    hiddenConsumer: false,
    personality: 'warm',
    voiceRate: 0.88,
    voicePitch: 0.8,
    description: "I'm the Geyser — the HOTTEST appliance in your home! 🔥 At 2,000 watts, I'm extremely powerful but used briefly. Heat water for just 10 minutes before your bath. A solar water heater can replace me and save ₹1,000+ per month!",
    researchNote: "Extremely high wattage, short use. Major saving if replaced with solar water heater. BEE star label mandatory.",
    funFact: "A solar water heater has zero running cost and can save ₹12,000+ per year compared to me!",
    source: 'BEE India S&L',
  },

  induction: {
    id: 'induction',
    name: 'Induction Cooktop',
    icon: '🍳',
    room: 'Kitchen',
    wattage: 1500,
    usePerDay: '1.5 hr/day',
    daysPerYear: 365,
    monthlyKwh: 67.5,
    annualKwh: 810,
    co2PerYear: +(810 * CO2_FACTOR).toFixed(1),
    category: 'Heating/Cooking',
    essential: true,
    beeRated: 'Voluntary',
    standbyPower: '0–1W',
    hiddenConsumer: false,
    personality: 'sizzling',
    voiceRate: 1.0,
    voicePitch: 1.0,
    description: "Sizzle sizzle! 🍳 I'm the Induction Cooktop! At 1,500W I sound energy-hungry, but I'm 85% efficient vs gas stoves at only 40%! I heat food faster, so total energy per meal is actually lower. I'm replacing LPG in modern Indian kitchens!",
    researchNote: "Replaces LPG. Very high wattage but 85% efficient vs 40% for gas. Essential if primary cooking method.",
    funFact: "I'm over twice as efficient as a gas stove — 85% vs 40%. The future of cooking is electric!",
    source: 'BEE India',
  },

  microwave: {
    id: 'microwave',
    name: 'Microwave Oven',
    icon: '📡',
    room: 'Kitchen',
    wattage: 1000,
    usePerDay: '30 min/day',
    daysPerYear: 300,
    monthlyKwh: 15,
    annualKwh: 150,
    co2PerYear: +(150 * CO2_FACTOR).toFixed(1),
    category: 'Heating/Cooking',
    essential: false,
    beeRated: 'Voluntary',
    standbyPower: '3–5W',
    standbyKwhYear: '26–44',
    hiddenConsumer: true,
    personality: 'buzzy',
    voiceRate: 1.05,
    voicePitch: 1.15,
    description: "BEEP BEEP! 📡 I'm the Microwave Oven! I use 1,000W when cooking, but here's my SECRET: my digital clock display runs 24/7, drawing 3–5W continuously even when I'm not cooking! That's 26–44 kWh/year just for showing the time! I'm a HIDDEN CONSUMER!",
    researchNote: "HIDDEN CONSUMER: Digital clock display runs 24/7 even when not cooking, drawing 3–5W continuously.",
    funFact: "My clock alone uses more electricity per year than charging your phone!",
    source: 'BEE India',
  },

  mixer_grinder: {
    id: 'mixer_grinder',
    name: 'Mixer Grinder',
    icon: '⚡',
    room: 'Kitchen',
    wattage: 600,
    usePerDay: '15 min/day',
    daysPerYear: 365,
    monthlyKwh: 4.5,
    annualKwh: 55,
    co2PerYear: +(55 * CO2_FACTOR).toFixed(1),
    category: 'Motors/Cooking',
    essential: true,
    beeRated: 'No',
    standbyPower: 0,
    hiddenConsumer: false,
    personality: 'energetic',
    voiceRate: 1.2,
    voicePitch: 1.3,
    description: "BRRRRR! ⚡ I'm the Mixer Grinder — fast and ENERGETIC! At 600 watts I sound powerful, but I only run for 15 minutes a day! My short burst usage keeps annual consumption super low at just 55 kWh/year. I'm a universal Indian kitchen hero!",
    researchNote: "Universal Indian kitchen appliance. Short burst usage keeps annual consumption low.",
    funFact: "Despite being 600W, I use less electricity per year than a single LED bulb left on 24/7!",
    source: 'Manufacturer specs',
  },

  wifi_router: {
    id: 'wifi_router',
    name: 'Wi-Fi Router',
    icon: '📶',
    room: 'Living Room',
    wattage: '6–12',
    usePerDay: '24 hr/day',
    daysPerYear: 365,
    monthlyKwh: '4.3–8.6',
    annualKwh: '53–105',
    co2PerYear: '38–75',
    category: 'Electronics/Comms',
    essential: true,
    beeRated: 'No',
    standbyPower: 'Always On',
    standbyKwhYear: '53–105',
    hiddenConsumer: true,
    personality: 'nerdy',
    voiceRate: 1.0,
    voicePitch: 1.1,
    description: "Connect... connect... 📶 I'm the Wi-Fi Router! I'm a HIDDEN CONSUMER — running 24/7/365 but everyone forgets about me because I'm only 6–12W. A typical 6W router uses ~53 kWh/year. Nobody ever switches me off... because nobody can live without me! 😄",
    researchNote: "HIDDEN CONSUMER: Runs 24/7/365 but overlooked due to low wattage. Typical 6W router = ~53 kWh/yr.",
    funFact: "I never sleep. 24 hours a day, 365 days a year. That's dedication!",
    source: 'Manufacturer; Airtel India; LBNL',
  },

  set_top_box: {
    id: 'set_top_box',
    name: 'Set-Top Box (DTH)',
    icon: '📦',
    room: 'Living Room',
    wattage: '10–25',
    usePerDay: '6 hr active + 18 hr standby',
    daysPerYear: 365,
    monthlyKwh: '7–18',
    annualKwh: '88–219',
    co2PerYear: '62–155',
    category: 'Electronics/Entertainment',
    essential: false,
    beeRated: 'No',
    standbyPower: '8–15W',
    standbyKwhYear: '70–131',
    hiddenConsumer: true,
    personality: 'sneaky',
    voiceRate: 0.9,
    voicePitch: 0.85,
    description: "Shhhh... 📦 I'm the Set-Top Box, the WORST HIDDEN CONSUMER in your home! My standby power (8–15W) is nearly the same as when I'm active! Most people never switch me off at the wall. The IEA flagged me globally as a major energy waster. Just turn me off at the plug!",
    researchNote: "WORST HIDDEN CONSUMER. Standby (8–15W) nearly equals active power. Most users never switch off at wall. IEA flagged globally.",
    funFact: "I waste 70–131 kWh/year just in standby — more than your ceiling fan uses all year!",
    source: 'U.S. DOE; IEA; BEE India',
  },

  // ─── NON-INTERACTABLE (environmental) appliances ───
  bldc_fan: {
    id: 'bldc_fan',
    name: 'BLDC Ceiling Fan',
    icon: '🌀',
    room: 'Bedroom',
    wattage: 28,
    annualKwh: 81,
    co2PerYear: +(81 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: true,
    description: "I'm the BLDC Fan — 60% more efficient than regular fans!",
    source: 'BEE India S&L',
  },
  table_fan: {
    id: 'table_fan',
    name: 'Table/Pedestal Fan',
    icon: '🌬️',
    room: 'Any',
    wattage: 50,
    annualKwh: 72,
    co2PerYear: +(72 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: true,
    description: "I'm the portable fan — supplementary cooling for any room!",
    source: 'BEE / Manufacturer',
  },
  led_tube: {
    id: 'led_tube',
    name: 'LED Tube Light (20W)',
    icon: '💡',
    room: 'Kitchen/Living',
    wattage: 20,
    annualKwh: 73,
    co2PerYear: +(73 * CO2_FACTOR).toFixed(1),
    category: 'Lighting',
    essential: true,
    description: "I replace a 40W fluorescent tube — half the energy, same brightness!",
    source: 'BEE India S&L',
  },
  ac_1ton: {
    id: 'ac_1ton',
    name: 'AC (1 Ton Inverter)',
    icon: '❄️',
    room: 'Bedroom/Living',
    wattage: 900,
    annualKwh: 1080,
    co2PerYear: +(1080 * CO2_FACTOR).toFixed(1),
    category: 'Cooling',
    essential: false,
    description: "I'm the 1 Ton AC — smaller but still a major energy user!",
    source: 'BEE India S&L',
  },
  tv_32: {
    id: 'tv_32',
    name: 'TV (32" LED)',
    icon: '📺',
    room: 'Living Room',
    wattage: 40,
    annualKwh: 88,
    co2PerYear: +(88 * CO2_FACTOR).toFixed(1),
    category: 'Electronics',
    essential: true,
    description: "I'm the basic LED TV — energy-efficient entertainment!",
    source: 'BEE India S&L',
  },
  phone_charger: {
    id: 'phone_charger',
    name: 'Phone Charger',
    icon: '🔌',
    room: 'Bedroom',
    wattage: '5–25',
    annualKwh: '18–27',
    co2PerYear: '13–19',
    category: 'Electronics/Charging',
    essential: true,
    standbyPower: '0.1–0.5W',
    hiddenConsumer: true,
    description: "I'm the Phone Charger — a tiny hidden consumer! I draw 0.1–0.5W even when no phone is connected.",
    source: 'U.S. DOE LBNL; BEE India',
  },
};

// ─── 3D Positions for all appliances ───
export const APPLIANCE_POSITIONS = {
  // Living Room
  ceiling_fan:    { pos: [-5, 2.85, -4],    rot: [0, 0, 0] },
  led_bulb:       { pos: [-3, 2.9, -6],     rot: [0, 0, 0] },
  tv_smart:       { pos: [-5, 1.0, -7.7],   rot: [0, 0, 0] },
  wifi_router:    { pos: [-9.7, 0.5, -2],    rot: [0, Math.PI / 2, 0] },
  set_top_box:    { pos: [-5, 0.45, -7.5],   rot: [0, 0, 0] },
  // Bedroom
  ac_1_5ton:      { pos: [9.7, 2.3, -4],    rot: [0, -Math.PI / 2, 0] },
  // Kitchen
  fridge:         { pos: [-1.5, 0.9, 7.2],  rot: [0, Math.PI, 0] },
  induction:      { pos: [-8.5, 0.95, 7.3], rot: [0, Math.PI, 0] },
  microwave:      { pos: [-6.5, 1.15, 7.3], rot: [0, Math.PI, 0] },
  mixer_grinder:  { pos: [-4.0, 0.95, 7.3], rot: [0, Math.PI, 0] },
  // Bathroom
  geyser:         { pos: [9.7, 2.0, 2],     rot: [0, -Math.PI / 2, 0] },
  washing_machine:{ pos: [5.5, 0.42, 7.2],  rot: [0, Math.PI, 0] },
};

// ─── Quiz Questions ───
export const QUIZ_QUESTIONS = [
  {
    id: 'q1',
    question: 'Which of these is NOT classified as an essential appliance?',
    options: ['Ceiling Fan', 'Air Conditioner', 'Refrigerator', 'LED Lights'],
    correctIndex: 1,
    explanation: 'ACs are classified as Non-Essential in the dataset. Fans are the primary essential cooling device in India.',
    source: 'D1 Dataset Classification',
  },
  {
    id: 'q2',
    question: 'A charger plugged in but not charging still uses electricity. True or False?',
    options: ['True', 'False'],
    correctIndex: 0,
    explanation: 'Idle chargers draw 0.1–0.5W. Confirmed by U.S. DOE LBNL and BEE India phantom load data.',
    source: 'U.S. DOE LBNL',
  },
  {
    id: 'q3',
    question: 'Which room typically has the MOST appliances?',
    options: ['Bathroom', 'Kitchen', 'Bedroom', 'Balcony'],
    correctIndex: 1,
    explanation: 'Kitchen has fridge, induction, microwave, mixer, LED tube = 5+ appliances.',
    source: 'D1 Dataset',
  },
  {
    id: 'q4',
    question: 'The Wi-Fi router runs how many hours per day?',
    options: ['6 hours', '12 hours', '24 hours', '8 hours'],
    correctIndex: 2,
    explanation: 'Wi-Fi routers run 24/7/365. Confirmed by Airtel India technical docs.',
    source: 'Airtel India',
  },
  {
    id: 'q5',
    question: 'Which appliance is the WORST hidden consumer in standby mode?',
    options: ['Microwave Oven', 'Wi-Fi Router', 'Set-Top Box', 'Phone Charger'],
    correctIndex: 2,
    explanation: 'Set-Top Box standby (8–15W) nearly equals its active power. IEA flagged it globally. It wastes 70–131 kWh/year in standby!',
    source: 'IEA; U.S. DOE',
  },
];

// ─── Idle Chatter Lines ───
export const IDLE_CHATTER = [
  "Hey! I'm over here, come talk to me!",
  "Psst... want to know a secret about energy?",
  "Don't ignore me! I have important facts!",
  "Come closer, I won't bite... I'll just enlighten you! 💡",
  "Did you know I'm wasting energy right now? Come find out how!",
  "Hey Arjun! Over here! 👋",
];
